version: '3.7'
networks:
  service-network:
    name: service-network
    driver: bridge
services:
  db-service:
    image: mongo:latest
    hostname: db-service
    volumes:
      - ./data/db:/data/db
    networks:
      - service-network
  api-service:
    container_name: api-service
    hostname: api-service
    image: ghcr.io/drupi0/url-api-service:latest
    restart: on-failure
    pull_policy: always
    environment:
      MONGO_URL: mongodb://db-service:27017
      ALLOWED_ORIGINS: "codersph.org shrinkly.cc"
    networks:
      - service-network
  ui-service:
    container_name: ui-service
    hostname: ui-service
    image: ghcr.io/drupi0/url-ui-service:latest
    restart: on-failure
    pull_policy: always
    ports:
      - 4200:80
    depends_on:
      - api-service
    networks:
      - service-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf